package ru.sfedu.airplane.models.constants;

public enum KeysForCli {

    CSV,
    XML,
    DB,

    ADDFLY,
    ADDPILOT,
    ADDBOMBER,
    ADDAGRICULTURAL,
    ADDFIREAIRCRAFT,
    ADDFITHER,
    ADDFREIGHT,
    ADDPASSENGER,

    GETFLY,
    GETPILOT,
    GETBOMBER,
    GETAGRICULTURAL,
    GETFIREAIRCRAFT,
    GETFITHER,
    GETFREIGHT,
    GETPASSENGER,

    DELFLY,
    DELPILOT,
    DELBOMBER,
    DELAGRICULTURAL,
    DELFIREAIRCRAFT,
    DELFITHER,
    DELFREIGHT,
    DELPASSENGER,

    UPDFLY,
    UPDPILOT,
    UPDBOMBER,
    UPDAGRICULTURAL,
    UPDFIREAIRCRAFT,
    UPDFITHER,
    UPDFREIGHT,
    UPDPASSENGER,

    CHECKPILOTCOUNT,
    CHECKPILOTLIST,
    CHECKPILOTCHECK,
    CHECKAIRCOUNT,
    CHECKAIRLIST,

    ADD, UPD;
}
